dist: jammy

sudo: required

language: python

python: "3.11"

services:
  - postgresql

install:
  - pip install tox-travis
  - pip install -r requirements.txt

script:
  - psql -c 'create database chatbot_test;' -U postgres
  - psql chatbot_test -c 'create extension pg_trgm;' -U postgres
  - psql chatbot_test -c 'create role chatbot superuser login; alter schema public owner to chatbot;' -U postgres
  - tox --parallel || travis_terminate 1